//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTb
    {
        public int ServiceId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public string Message { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual VehicleTb VehicleTb { get; set; }
    }
}
